### PR TITLE
feat(cd): deploy main continuously to sectracker.nixpkgs.lahfa.xyz

### PR DESCRIPTION
**Pull request by RaitoBezarius**
This is a dumb CD system, but sufficient for now.

### CODE REVIEW

**Comment by fricklerhandwerk** [comment]
Doesn't this need secrets set up in this repo or something?

**Comment by RaitoBezarius** [comment]
We need to add the CI deployment SSH key to the host, yes.

**Comment by RaitoBezarius** [comment]
This is now done.

**Comment by RaitoBezarius** [comment]
The security tracker is failing in the staging environment, but that's unrelated to this PR.

**Comment by fricklerhandwerk** [comment]
@RaitoBezarius noted that the server is still crashing, this is probably due to https://github.com/Nix-Security-WG/nix-security-tracker/issues/240

**Pull request merged**
