### PR TITLE
feat(models): improve the Nix evaluation data models

### PR DESCRIPTION
**Pull request by fricklerhandwerk**
We now have more fields for the evaluation, and timestamping in preparation
for managing the Nixpkgs repository.

as part of breaking down #123

### CODE REVIEW

**Comment by RaitoBezarius** [comment]
Please hold off with this PR, I am not totally done with the fields yet.

**Comment by fricklerhandwerk** [comment]
Yep, there are a few future commits which still change them. I'd like to have as many changes at once as possible, otherwise we'll just be piling up migrations.

**Comment by RaitoBezarius** [comment]
> Yep, there are a few future commits which still change them. I'd like to have as many changes at once as possible, otherwise we'll just be piling up migrations.

The goal is to avoid having 50 migrations, so while I am developing in the branch, if you chip away individual migrations, I cannot squash them anymore.

**Comment by fricklerhandwerk** [comment]
Generally, can we squash away all migrations before we deploy to production?

**Comment by RaitoBezarius** [comment]
We can but I don't recommend squashing migrations more than necessary, they are valuable development knowledge. I recommend squashing migrations done too hastily in development.

**Comment by RaitoBezarius** [comment]
#123 is ready, I propose to hop on this one rather and merge it directly.

**Pull request closed without merging**
