### PR TITLE
feat(operations): deploy sectracker.nixpkgs.lahfa.xyz

### PR DESCRIPTION
**Pull request by RaitoBezarius**
A pretty classical thing, reusing our work so far.

### CODE REVIEW

**Comment by RaitoBezarius** [comment]
Deployed.

**Comment by RaitoBezarius** [comment]
@Tom-Hubrecht Please add your keys to the deployment, and I was not able to run the ingestion because:
```

[root@staging:/var/lib/web-security-tracker]# wst-manage ingest_bulk_cve
GH_CLIENT_ID:/etc/secrets/gh-client GH_SECRET:/etc/secrets/gh-secret SECRET_KEY:/etc/secrets/django-secret-key
Running as unit: wst-manage.service
Press ^] three times within 1s to disconnect TTY.
No token available in the credentials directory, using unauthenticated API.
Wrong bundle asset: 2023-12-04_delta_CVEs_at_end_of_day.zip
CommandError: Unable to get bundled CVEs.
```

I suggest to:

(a) Get real secrets for the tokens
(b) Debug this and put it in a tmux and run it

**Comment by RaitoBezarius** [comment]
Also, please fix the GH app as I am not admin of the org alas.

**Comment by 06kellyjac** [comment]
No lets encrypt?

**Comment by RaitoBezarius** [comment]
LE doesn't want to understand IPv6, should fix soon

**Pull request merged**
